module.exports = {
  //Defines properties
  name: "glados",
  description:
    "TTS Engine that sounds like GLaDOS! | Generated by https://glados.c-net.org/",
  usage: "TTS input",
  cooldown: 120,
  //code to be executed
  async execute(message, args, displayColor) {
    const { curly } = require("node-libcurl");
    var tts = args.join(" ");
    message.channel.send({
      embed: {
        color: displayColor,
        //sets the time of the request being made
        timestamp: new Date(),
        footer: {
          text: `Requested by ${message.author.username}`,
          icon_url: `https://cdn.discordapp.com/avatars/${message.author.id}/${message.author.avatar}.png`
        },
        fields: [
          {
            name: "Proccessing messsage:",
            value:
              "*" + tts + "*\nData is proccessed by https://glados.c-net.org/"
          }
        ]
      }
    });
    message.channel.startTyping();
    tts = encodeURI(tts);
    console.log(tts);
    const { data } = await curly.get(
      `https://glados.c-net.org/generate?text=` + tts
    );
    var url =
      "https://glados.c-net.org/" +
      data.replace("Your sample is available at: ", "");
    console.log(data);
    message.channel.send(url);
    message.channel.send({
      files: [url]
    });
    message.channel.stopTyping(true);
  }
};

function error(message) {
  message.channel.send("An Error occurred!");
  message.channel.stopTyping(true);
  return;
}
